{% set name = "solt" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aegoroff/solt/archive/v{{ version }}.tar.gz
  sha256: 7989ae162f5d417d210cd288149d6b60e5c2ee1563d8e5816989e86aede24092

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - solt --help

about:
  home: https://github.com/aegoroff/solt
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Small console app written in Go that allows you to easily analyze sources and Microsoft Visual Studio solutions and projects.
  dev_url: https://github.com/aegoroff/solt

extra:
  recipe-maintainers:
    - danielnachun
