schema_version: 1

context:
  version: "1.3.1"

package:
  name: solt
  version: ${{ version }}

source:
  url: https://github.com/aegoroff/solt/archive/v${{ version }}.tar.gz
  sha256: 9089e3a11a5b89b7b483bba496223aea21d19fed9ab9464db40b4a5b617f7ca7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - solt --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Small console app written in Go that allows you to easily analyze sources and Microsoft Visual Studio solutions and projects.
  homepage: https://github.com/aegoroff/solt
  repository: https://github.com/aegoroff/solt

extra:
  recipe-maintainers:
    - danielnachun
